services:
  not_app:
    build:
      context: .
      args:
        SERVICE_NAME: not-sale-back
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: not_postgres
      PG_PORT: 5432
      PG_DB: app
      REDIS_HOST: not_redis
      REDIS_PORT: 6379
    depends_on:
      - not_postgres
      - not_redis

  not_postgres:
    image: postgres:17.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - not_sale_pg:/var/lib/postgresql/data:Z
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d app -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 10

  not_redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - not_sale_redis:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  not_sale_pg:
    driver: local
  not_sale_redis:
    driver: local
