### Checkout an item
POST http://localhost:8080/checkout?user_id=user123&id=1

### Purchase an item (replace CODE with the code from the checkout response)
POST http://localhost:8080/purchase?code=w6_sOn8ZaEDdlLIcRKImew==
